all: main main_prof main_narro

main: main.c
	gcc -Wall -o main main.c

main_prof: main_prof.c
	gcc -Wall -o main_prof main_prof.c

main_narro: main_narro.c
	gcc -Wall -o main_narro main_narro.c

clean: 
	rm main main_prof
